create table
  public.guests (
    id bigint generated by default as identity not null,
    first_name text null,
    last_name text null,
    genre smallint not null,
    status smallint not null default '1'::smallint,
    invitation_id bigint null,
    ticket_id bigint null,
    created_at timestamp with time zone null default now(),
    deleted_at timestamp with time zone null,
    constraint guests_pkey primary key (id),
    constraint guests_invitation_id_fkey foreign key (invitation_id) references invitations (id),
    constraint guests_ticket_id_fkey foreign key (ticket_id) references tickets (id)
  ) tablespace pg_default;