create table
  public.surveys (
    id bigint generated by default as identity not null,
    data json not null,
    invitation_id bigint null,
    created_at timestamp with time zone null default now(),
    constraint surveys_pkey primary key (id),
    constraint surveys_invitation_id_fkey foreign key (invitation_id) references invitations (id) on delete cascade
  ) tablespace pg_default;